package PAT;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Banzile Nhlebela
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword3
     */
    
    private Connection con = null;
    private PreparedStatement pst = null;
    private PreparedStatement ps = null;
    
    public ForgotPassword()
    {
        initComponents();
        //code to make form appear in center of screen
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
        //disable Enter button
        btnEnter.setEnabled(false);
        //Disable password fields and text fields
        pfNPass.setEnabled(false);
        pfCPass.setEnabled(false);
        txtANS.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        WhiteBand = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHelp = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblANS = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtCUN = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();
        lblCP = new javax.swing.JLabel();
        lblCPeye = new javax.swing.JLabel();
        pfNPass = new javax.swing.JPasswordField();
        lblNPeye = new javax.swing.JLabel();
        lblNP = new javax.swing.JLabel();
        txtANS = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        pfCPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgot Password");
        setName("Forgot Password"); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        WhiteBand.setBackground(new java.awt.Color(255, 255, 255));
        WhiteBand.setForeground(new java.awt.Color(255, 255, 255));
        WhiteBand.setPreferredSize(new java.awt.Dimension(731, 216));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("ENJABULWENI SCHOOL");

        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("\"Sifundza Kanyekanye\" - Together we Learn");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\eliznab74\\Pictures\\Badge.jpg")); // NOI18N

        lblHelp.setForeground(new java.awt.Color(0, 0, 0));
        lblHelp.setText("Help");
        lblHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHelpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout WhiteBandLayout = new javax.swing.GroupLayout(WhiteBand);
        WhiteBand.setLayout(WhiteBandLayout);
        WhiteBandLayout.setHorizontalGroup(
            WhiteBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WhiteBandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WhiteBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHelp)
                    .addGroup(WhiteBandLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WhiteBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(WhiteBandLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        WhiteBandLayout.setVerticalGroup(
            WhiteBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WhiteBandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WhiteBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(WhiteBandLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(88, 88, 88)
                        .addComponent(lblHelp))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(WhiteBand, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 680, -1));

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jPanel3.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 680, 20));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        lblANS.setBackground(new java.awt.Color(0, 0, 0));
        lblANS.setForeground(new java.awt.Color(255, 255, 255));
        lblANS.setText("Answer:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Current Username:");

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 204, 0));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtCUN.setBackground(new java.awt.Color(0, 0, 0));
        txtCUN.setForeground(new java.awt.Color(255, 204, 0));
        txtCUN.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(255, 204, 0)));

        btnReturn.setBackground(new java.awt.Color(0, 0, 0));
        btnReturn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 204, 0));
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        lblCP.setBackground(new java.awt.Color(0, 0, 0));
        lblCP.setForeground(new java.awt.Color(255, 255, 255));
        lblCP.setText("Confirm Password:");

        lblCPeye.setIcon(new javax.swing.ImageIcon("C:\\Users\\eliznab74\\Documents\\NetBeansProjects\\IT PAT\\closed.png")); // NOI18N
        lblCPeye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCPeye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCPeyeMouseClicked(evt);
            }
        });

        pfNPass.setBackground(new java.awt.Color(0, 0, 0));
        pfNPass.setForeground(new java.awt.Color(255, 204, 0));
        pfNPass.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(255, 204, 0)));
        pfNPass.setCaretColor(new java.awt.Color(0, 0, 0));
        pfNPass.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        lblNPeye.setIcon(new javax.swing.ImageIcon("C:\\Users\\eliznab74\\Documents\\NetBeansProjects\\IT PAT\\closed.png")); // NOI18N
        lblNPeye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNPeye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNPeyeMouseClicked(evt);
            }
        });

        lblNP.setBackground(new java.awt.Color(0, 0, 0));
        lblNP.setForeground(new java.awt.Color(255, 255, 255));
        lblNP.setText("New Password:");

        txtANS.setBackground(new java.awt.Color(0, 0, 0));
        txtANS.setForeground(new java.awt.Color(255, 204, 0));
        txtANS.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(255, 204, 0)));

        btnEnter.setBackground(new java.awt.Color(0, 0, 0));
        btnEnter.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(255, 204, 0));
        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        pfCPass.setBackground(new java.awt.Color(0, 0, 0));
        pfCPass.setForeground(new java.awt.Color(255, 204, 0));
        pfCPass.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(255, 204, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtCUN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblNP)
                        .addGap(278, 278, 278)
                        .addComponent(lblANS))
                    .addComponent(lblCP)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pfCPass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCPeye)
                        .addGap(124, 124, 124)
                        .addComponent(btnReturn)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnter)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pfNPass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblNPeye)
                        .addGap(118, 118, 118)
                        .addComponent(txtANS, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(txtCUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNP)
                    .addComponent(lblANS))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pfNPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNPeye)
                    .addComponent(txtANS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblCP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pfCPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPeye))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearch)
                            .addComponent(btnEnter)
                            .addComponent(btnReturn))
                        .addContainerGap())))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 680, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        //dispaly login page
        LoginPage log = new LoginPage();
        log.setVisible(true);
        //close current screen
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        //colours and borders used to indicate errors or success
        Color r = new Color(156, 0, 0);
        Color g = new Color(15, 165, 7);
        
        Border b = BorderFactory.createMatteBorder(1, 1, 3, 1, r);
        Border a = BorderFactory.createMatteBorder(1, 1, 3, 1, g);
        
        //begin try-catch
        try
        {
            //get connection to database
            con = DriverManager.getConnection("jdbc:mysql://localhost/consultations", "root", "");
            String query = "SELECT * FROM security WHERE `Username` = '" + txtCUN.getText() + "'";
            pst = con.prepareStatement(query);
            //obtain result of query from database
            ResultSet rs = pst.executeQuery(query);
            
            //if username found
            if(rs.next())
            {
                //endable enter button
                btnEnter.setEnabled(true);
                //make username field green
                txtCUN.setForeground(g);
                txtCUN.setBorder(a);
                //disable username field and 'Search' button
                txtCUN.setEnabled(false);
                btnSearch.setEnabled(false);
                //enable answer field
                txtANS.setEnabled(true);
                //display message indicating success
                JOptionPane.showMessageDialog(null, "Username found" + "\nAnswer Security Question in the space provided" + "\nThen select \'Enter\'");
                //display security question
                JOptionPane.showMessageDialog(null, rs.getString("Question"));
            }
            //if username not found
            else
            {
                //display message indicating error
                JOptionPane.showMessageDialog(null, "Username Not Found", "Error", JOptionPane.ERROR_MESSAGE);
                //turn username field red to indicate error
                txtCUN.setForeground(r);
                txtCUN.setBorder(b);
                txtCUN.requestFocus();
            }
            //close connection to database
            con.close();
        }
        catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void lblHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHelpMouseClicked
        // TODO add your handling code here:
        //display help screen
        Help h = new Help();
        h.setVisible(true);
    }//GEN-LAST:event_lblHelpMouseClicked

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        //colours and borders used to indicate success or error
        Color re = new Color(156, 0, 0);
        Color g = new Color(15, 165, 7);
        
        Border b = BorderFactory.createMatteBorder(1, 1, 3, 1, re);
        Border a = BorderFactory.createMatteBorder(1, 1, 3, 1, g);
        
        //if answer field is enabled
        if(txtANS.isEnabled())
        {
            //begin try-catch
            try
            {
                //get connection to database
                con = DriverManager.getConnection("jdbc:mysql://localhost/consultations", "root", "");
                String query = "SELECT * FROM security WHERE `Answer` = '" + txtANS.getText() + "'";
                pst = con.prepareStatement(query);
                //search for answer with regards to question and username
                ResultSet rs = pst.executeQuery(query);
                
                String query2 = "SELECT * FROM security WHERE `Username` = '" + txtCUN.getText() + "'";
                ps = con.prepareStatement(query2);
                ResultSet r = ps.executeQuery(query2);
                
                //if answer matches question and username
                if(rs.next())
                {
                    //make field green to indicate correct answer
                    txtANS.setBorder(a);
                    txtANS.setForeground(g);
                    //display message indicating next step
                    JOptionPane.showMessageDialog(null, "Correct Answer.\n" + "Enter new Password\n" + "Then select 'Enter'");
                    //enable password fields and disable answer field
                    pfNPass.setEnabled(true);
                    pfCPass.setEnabled(true);
                    txtANS.setEnabled(false);
                }
                //if answer is wrong
                else
                {
                    //set field to red to indicate error
                    txtANS.setBorder(b);
                    txtANS.setForeground(re);
                    //display message explaining error
                    JOptionPane.showMessageDialog(null, "Incorrect Answer", "Error", JOptionPane.ERROR_MESSAGE);
                    //display question again
                    if(r.next())
                    {
                        JOptionPane.showMessageDialog(null, r.getString("Question"));
                    }
                }
            }
            catch(HeadlessException | SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
            //end of try catch
        }
        //if answer has already been entered (answer field now disabled)
        else
        {
            LoginPage log = new LoginPage();
            //begin try-catch
            try
            {
                //get connection to database
                con = DriverManager.getConnection("jdbc:mysql://localhost/consultations", "root", "");
                String query = "UPDATE accountdetails SET `Password` = ? WHERE `Username` = '" + txtCUN.getText() + "'";
                pst = con.prepareStatement(query);

                //if new password and confirm password are the same
                if(pfNPass.getText().equals(pfCPass.getText()))
                {
                    //update security database
                    pst.setString(1, pfCPass.getText());
                    pst.executeUpdate();
                    //set both fields to green to indicate success
                    pfCPass.setBorder(a);
                    pfNPass.setBorder(a);
                    pfCPass.setForeground(g);
                    pfNPass.setForeground(g);
                    //display message indicating success
                    JOptionPane.showMessageDialog(null, "Password Changed Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    //display login form
                    log.setVisible(true);
                    //close current screen
                    this.dispose();
                }
                //if passwords do not match
                else
                {
                    //make both fields red to indicate error
                    pfCPass.setBorder(b);
                    pfNPass.setBorder(b);
                    pfCPass.setForeground(re);
                    pfNPass.setForeground(re);
                    //display message explaining error
                    JOptionPane.showMessageDialog(null, "Passwords Do Not Match", "Failure", JOptionPane.ERROR_MESSAGE);
                }
            }    
            catch(HeadlessException | SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
            //end of try-catch
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void lblNPeyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNPeyeMouseClicked
        // TODO add your handling code here:
        //images used for password eye
        ImageIcon open = new ImageIcon("open.png");
        ImageIcon closed = new ImageIcon("closed.png");
        
        if(lblNPeye.getIcon().toString().endsWith("closed.png"))
        {
            lblNPeye.setIcon(open);
            pfNPass.setEchoChar((char)0);
        }
        else
        {
            lblNPeye.setIcon(closed);
            pfNPass.setEchoChar('*');
        }
    }//GEN-LAST:event_lblNPeyeMouseClicked

    private void lblCPeyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCPeyeMouseClicked
        // TODO add your handling code here:
        //images used for password eye
        ImageIcon open = new ImageIcon("open.png");
        ImageIcon closed = new ImageIcon("closed.png");
        
        if(lblCPeye.getIcon().toString().endsWith("closed.png"))
        {
            lblCPeye.setIcon(open);
            pfCPass.setEchoChar((char)0);
        }
        else
        {
            lblCPeye.setIcon(closed);
            pfCPass.setEchoChar('*');
        }
    }//GEN-LAST:event_lblCPeyeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ForgotPassword().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WhiteBand;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblANS;
    private javax.swing.JLabel lblCP;
    private javax.swing.JLabel lblCPeye;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblNP;
    private javax.swing.JLabel lblNPeye;
    private javax.swing.JPasswordField pfCPass;
    private javax.swing.JPasswordField pfNPass;
    private javax.swing.JTextField txtANS;
    private javax.swing.JTextField txtCUN;
    // End of variables declaration//GEN-END:variables
}
