package PAT;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 * @author Banzile Nhlebela
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    public MainMenu()
    {
        initComponents();
        //code to make screen appear in center of device screen
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        blueBand = new javax.swing.JPanel();
        WhiteBand = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDisplay = new javax.swing.JLabel();
        YellowBand = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        lblUNerr = new javax.swing.JLabel();
        lblPwdErr = new javax.swing.JLabel();
        btnSL = new javax.swing.JButton();
        btnOR = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnEP = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnPL = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setName("Main Menu"); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blueBand.setBackground(new java.awt.Color(0, 0, 102));
        blueBand.setForeground(new java.awt.Color(0, 0, 102));
        blueBand.setPreferredSize(new java.awt.Dimension(731, 243));

        WhiteBand.setBackground(new java.awt.Color(255, 255, 255));
        WhiteBand.setForeground(new java.awt.Color(255, 255, 255));
        WhiteBand.setPreferredSize(new java.awt.Dimension(731, 216));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("ENJABULWENI SCHOOL");

        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("\"Sifundza Kanyekanye\" - Together we Learn");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\eliznab74\\Pictures\\Badge.jpg")); // NOI18N

        javax.swing.GroupLayout WhiteBandLayout = new javax.swing.GroupLayout(WhiteBand);
        WhiteBand.setLayout(WhiteBandLayout);
        WhiteBandLayout.setHorizontalGroup(
            WhiteBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WhiteBandLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addGroup(WhiteBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(508, 508, 508))
        );
        WhiteBandLayout.setVerticalGroup(
            WhiteBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WhiteBandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WhiteBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WhiteBandLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblDisplay.setBackground(new java.awt.Color(255, 255, 255));
        lblDisplay.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout blueBandLayout = new javax.swing.GroupLayout(blueBand);
        blueBand.setLayout(blueBandLayout);
        blueBandLayout.setHorizontalGroup(
            blueBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WhiteBand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1210, Short.MAX_VALUE)
            .addGroup(blueBandLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDisplay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        blueBandLayout.setVerticalGroup(
            blueBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blueBandLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WhiteBand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(blueBand, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1205, -1));

        YellowBand.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout YellowBandLayout = new javax.swing.GroupLayout(YellowBand);
        YellowBand.setLayout(YellowBandLayout);
        YellowBandLayout.setHorizontalGroup(
            YellowBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        YellowBandLayout.setVerticalGroup(
            YellowBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(YellowBand, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 830, 20));

        btnLogOut.setBackground(new java.awt.Color(0, 0, 0));
        btnLogOut.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 204, 0));
        btnLogOut.setText("Log Out");
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));
        jPanel1.add(lblUNerr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));
        jPanel1.add(lblPwdErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        btnSL.setBackground(new java.awt.Color(0, 0, 0));
        btnSL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSL.setForeground(new java.awt.Color(255, 204, 0));
        btnSL.setText("Student Log");
        btnSL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSLActionPerformed(evt);
            }
        });
        jPanel1.add(btnSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        btnOR.setBackground(new java.awt.Color(0, 0, 0));
        btnOR.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnOR.setForeground(new java.awt.Color(255, 204, 0));
        btnOR.setText("Offence Reg");
        btnOR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnORActionPerformed(evt);
            }
        });
        jPanel1.add(btnOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        btnHelp.setBackground(new java.awt.Color(0, 0, 0));
        btnHelp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(255, 204, 0));
        btnHelp.setText("Help");
        btnHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanel1.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        btnEP.setBackground(new java.awt.Color(0, 0, 0));
        btnEP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEP.setForeground(new java.awt.Color(255, 204, 0));
        btnEP.setText("Edit Profile");
        btnEP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEPActionPerformed(evt);
            }
        });
        jPanel1.add(btnEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        btnO.setBackground(new java.awt.Color(0, 0, 0));
        btnO.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnO.setForeground(new java.awt.Color(255, 204, 0));
        btnO.setText("Offences");
        btnO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });
        jPanel1.add(btnO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        btnPL.setBackground(new java.awt.Color(0, 0, 0));
        btnPL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPL.setForeground(new java.awt.Color(255, 204, 0));
        btnPL.setText("Parent Log");
        btnPL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPLActionPerformed(evt);
            }
        });
        jPanel1.add(btnPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\eliznab74\\Pictures\\R2.jpeg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 730, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        //Display confimation message asking user if they wish to log out
        int opt = JOptionPane.showConfirmDialog(null, "You are about to Log Out. Do you wish to proceed?", "Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        //if user clicks yes
        if(opt == 0)
        {
            LoginPage log = new LoginPage();
            //reset temp.txt file 
            try
            {
                try (PrintWriter px = new PrintWriter(new FileWriter(new File("temp.txt"))))
                {
                    px.print("username#password#position");
                }
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
            //set login oage to be visible
            log.setVisible(true);
            //close current screen
            this.dispose();
        }
        //if user clicks no
        else
        {
            //display message
            JOptionPane.showMessageDialog(null, "Log Out action aborted", "Log Out", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSLActionPerformed
        // TODO add your handling code here:
        //set student log screen to be visible
        StudentLog stulog = new StudentLog();
        stulog.setVisible(true);
        //close current screen
        this.dispose();
    }//GEN-LAST:event_btnSLActionPerformed

    private void btnEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEPActionPerformed
        // TODO add your handling code here:
        //set edit profile screen to be visible
        EditProfile ep = new EditProfile();
        ep.setVisible(true);
        //close current screen
        this.dispose();
    }//GEN-LAST:event_btnEPActionPerformed

    private void btnORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnORActionPerformed
        // TODO add your handling code here:
        //set offence register form to be visible
        StudentOffenceRegister con = new StudentOffenceRegister();
        con.setVisible(true);
        //close current screen
        this.dispose();
    }//GEN-LAST:event_btnORActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        //set help screen to be visible
        Help h = new Help();
        h.setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPLActionPerformed
        // TODO add your handling code here:
        //set parent log form to be visible
        ParentLog pl = new ParentLog();
        pl.setVisible(true);
        //close current screen
        this.dispose();
    }//GEN-LAST:event_btnPLActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        // TODO add your handling code here:
        //set offence log form to be visible
        OffenceLog off = new OffenceLog();
        off.setVisible(true);
        //close current screen
        this.dispose();
    }//GEN-LAST:event_btnOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WhiteBand;
    private javax.swing.JPanel YellowBand;
    private javax.swing.JPanel blueBand;
    private javax.swing.JButton btnEP;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnOR;
    private javax.swing.JButton btnPL;
    private javax.swing.JButton btnSL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JLabel lblPwdErr;
    private javax.swing.JLabel lblUNerr;
    // End of variables declaration//GEN-END:variables
}
